name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "2 * * *"
  #push:
  #  branches: 
  #    - master
  # Manual triggers with workflow_dispatch
  #workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        #uses: matchai/waka-box@master
        uses: Estella-lwl/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ff7331c8581072dfa316b1e95e7656ca
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          #SHOW_LANGUAGE : True
          #SHOW_OS : True
          #SHOW_EDITORS : True
